version: '3.8'

services:
  nestapi:
    image: nestapi
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    #   CATSAPI: https://api.thecatapi.com/v1/breeds
    #   CACHETTL: 5000
    volumes:
      - .:/src/
    ports:
      - 3333:3333

# docker-compose up
