apiVersion: v1
kind: Service
metadata:
  name: nestapi-service
spec:
  type: NodePort
  selector:
    app: nestapi
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      name: nestapi-service
